name: CI

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "**/*.rs"
      - "**/*.sh"
      - "**/*.ps1"
      - "**/*.toml"
      - ".github/workflows/**/*.yml"
      - "xtask/**"
      - "!**/*.md"
      - "!LICENSE"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "Cargo.lock"
      - "**/*.rs"
      - "**/*.sh"
      - "**/*.ps1"
      - "**/*.toml"
      - ".github/workflows/**/*.yml"
      - "xtask/**"
      - "!**/*.md"
      - "!LICENSE"

env:
  RUST_PREVIOUS_VERSION: "1.95.0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-checks:
    runs-on: ubuntu-latest
    outputs:
      rust-prev-version: ${{ env.RUST_PREVIOUS_VERSION }}
    steps:
      - name: Do Nothing
        if: false
        run: echo

  code-quality:
    runs-on: ubuntu-22.04
    needs: prepare-checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Install nightly rustfmt
        run: rustup toolchain install nightly --component rustfmt

      - name: Install quality tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-deny,typos-cli

      - name: Audit
        run: cargo xtask check audit

      - name: Format
        env:
          TERM: xterm-256color
        run: cargo xtask check format

      - name: Lint
        run: cargo xtask check lint

      - name: Typos
        run: cargo xtask check typos

  documentation:
    runs-on: ubuntu-22.04
    needs: prepare-checks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install book tooling
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook

      - name: Documentation Build
        run: cargo xtask doc build

      - name: Documentation Tests
        run: cargo xtask doc tests

      - name: Book Build
        run: cargo xtask books rwkv build

  linux-std-tests:
    runs-on: ubuntu-22.04
    needs: [prepare-checks, code-quality]
    strategy:
      matrix:
        rust: [stable, prev]
        include:
          - rust: stable
            toolchain: stable
            enable_coverage: true
          - rust: prev
            toolchain: ${{ needs.prepare-checks.outputs.rust-prev-version }}
            enable_coverage: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install test tooling
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov

      - name: Tests
        run: cargo xtask test --release --ci github-runner

      - name: Generate coverage
        if: matrix.enable_coverage
        run: cargo xtask coverage generate --profile release --ignore "target/*,xtask/*,examples/*"

      - name: Upload coverage
        if: matrix.enable_coverage
        uses: codecov/codecov-action@v5
        with:
          files: target/coverage/lcov.info

  linux-no-std-tests:
    runs-on: ubuntu-22.04
    needs: [prepare-checks, code-quality]
    strategy:
      matrix:
        rust: [stable, prev]
        include:
          - rust: stable
            toolchain: stable
          - rust: prev
            toolchain: ${{ needs.prepare-checks.outputs.rust-prev-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: No-std Build
        run: cargo xtask --context no-std build --ci

      - name: No-std Tests
        run: cargo xtask --context no-std test --release --ci github-runner

  windows-std-tests:
    runs-on: windows-2022
    needs: [prepare-checks, code-quality]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Tests
        run: cargo xtask test --release --ci github-runner

  macos-std-tests:
    runs-on: macos-15
    needs: [prepare-checks, code-quality]
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Device check
        run: system_profiler SPHardwareDataType

      - name: Tests
        run: cargo xtask test --release --ci github-mac-runner
