name: Dependencies

on:
  schedule:
    - cron: "0 21 * * TUE"
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly

      - name: Install dependency tooling
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-deny,cargo-udeps

      - name: Dependency suite
        run: cargo xtask dependencies
